title: Filippo Saccomano
logo: /assests/chickenjoe.jpeg
description: Hi! I am a Biomedical Engineer passionate about the intersection of data science, AI, and healthcare technology. Currently, I am pursuing my MSc in Information Bioengineering at Politecnico di Milano, after graduating from the University of Pavia.
show_downloads: true
theme: jekyll-theme-minimal
